"use strict";
exports.__esModule = true;
var _02_questao_1 = require("./02_questao");
var func1 = new _02_questao_1.Funcionario('Tommy Vercetti', 45000);
var func2 = new _02_questao_1.Funcionario('Franklin', 25000);
var func3 = new _02_questao_1.Funcionario('Michael', 7000);
var func4 = new _02_questao_1.Funcionario('Trevor', 1000);
func1.MostrarSalario();
func2.MostrarSalario();
func3.MostrarSalario();
func4.MostrarSalario();
